### PR TITLE
Increase stability parameter and fix fuel imbalance issue.

### LINKED ISSUE #40: Aircraft rolls when FPS are low
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-05-22T11:47:48+00:00",
    "ref": "refs/tags/v0.200",
    "sha": "89b88a85942045ce719bdcd7fd24002e2e0b196c",
    "actor": "Revyn112",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.200"
}
```

### Describe the bug

Severe rolling when FPS get low

### Expected behavior

Aircraft would maintain straight and level flight

### Steps to reproduce

1. Configure the sim in such a way that the FPS would be lowered
2. Take off and monitor for a rolling motion

### References (optional)

_No response_

### Additional info (optional)

- Issue started when the first big update (V1?) was released and is still an issue in V2
- Issue is not seen when flying the FBW A32NX, therefore is individual to the A339
- Issue persists even when the autopilot is disconnected, therefore it is not linked to the autopilot's minimum FPS requirement

### Discord Username (optional)

mightymackrel#4899

### PR DESCRIPTION
**Pull request by kevinwidjaja21**
So, the fuel imbalance is caused by the FADEC reading the fuel quantity to determined the center fuel capacity. Unfortunately, the value being read is the current wing capacity instead of the max wing capacity. Solution is to give a fix value of max fuel capacity in lbs - 0.1 lbs as margin. 

I also tweak the aircraft stability in the flight model so hopefully it fix the rolling issue during low FPS

Fixes #40

## Summary of Changes

- fix wing capacity parameter in the FADEC to (11095 gal * 6.7 lbs/gal) - 0.1 lbs
- decrease roll and yaw stability (according to the documentation, reducing these value will actually improve stability)
- Increase gyro stability

## Additional context

- I encounter some issue with the refuel page in which it doesn't refuel properly. But this might be just me broke something in my local copy.

Discord username (if different from GitHub):

## Testing instructions

- Perform a normal flight with both central tank empty and containing some fuel (don't need to be full)
- Test autopilot in low FPS condition.

## How to download the PR for Testing

Every new commit to this PR will cause a new A330-900neo artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **HEADWIND-A339** download link at the bottom of the page

### CODE REVIEW

**Comment by st3ph29** [comment]
Tested with 12.9 T on board, all pumps "ON", center tank empty. APU "on" until engines Start then off before TO. No "fuel leaks" toward the center, 20 kgs imbalance between Inner left (2210 kgs) and right  (2230 kgs).
Tested with 77 t and 3750 kgs on center. All pumps "ON". APU "on" until engines Start then off before TO. Center emptied as expected. Same imbalance of 20 kgs. Those two test flights were about 1h30 long (gate to gate)

Issue seems to be fixed.  To be confirmed on a Long haul flight.

**Review by Revyn112 — APPROVED** [review]

**Comment by CAC14** [comment]
After 8 hours there is still a slight imbalance, but it's a way better. 
I started with 6460, 74340, 30780, 74340, 6560
After 8-9 hours I have 6460, 18040, 0 , 18400, 6560
(all in pounds not kilo)

But the bigger problem is performance.  I'm not sure why the fuel update changed this, but she climbs horribly.  From fl 150-300 fully loaded i could only get 500 fpm.  After burning fuel my gross weight is 341000 which is well bellow MTOW.  I still can't get it to climb above fl310 quickly.  took 30 min to go from FL310-350.

**Comment by st3ph29** [comment]
Certainly a wrong install of the fix. There's no reason to tranfer "outer right" to "inner right" with a that amount of fuel remaining.
Delete the mod in community, delete the headwind file in "app data" and proceed to a fresh install. check the "clean install" on the FBW website.

**Comment by MicahBCode** [comment]
Fuel imbalance might be nearly fixed. But the climb profile is horrible with this PR! Hopefully gonna be fixed soon.

**Comment by Revyn112** [comment]
A Pull Request is not a valid general build. Most likely a pull request issue on specific problem for a fix or add one new feature to the addon. This PR build is only attempt to fix fuel imbalance - not climb profile. So using a PR build is not safe for a flight, because it will be have bugs as this a development builds. Please wait for an official update to use our addon on your flights.Holen Sie sich Outlook für Android

**Pull request merged**
